name: Deploy Stack

env:
  TERRAFORM_VERSION: latest
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to apply: '
        required: true
        type: choice
        default: dev
        options:
        - dev
        - prod
        - all

jobs:
  terraform-deploy-dev:
    name: Trigger Applying (dev)
    uses: ./.github/workflows/deploy.yml

    if: inputs.environment == 'dev' || inputs.environment == 'all' || inputs.environment == ''

    with:
      environment: dev
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_admin_role_arn: ${{ secrets.TF_VAR_ADMIN_ROLE_ARN }}

  terraform-deploy-prod:
    name: Trigger Applying (prod)
    uses: ./.github/workflows/deploy.yml

    if: inputs.environment == 'prod' || inputs.environment == 'all'

    with:
      environment: prod
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_admin_role_arn: ${{ secrets.TF_VAR_ADMIN_ROLE_ARN }}
