name: Deploy Stack

env:
  TERRAFORM_VERSION: latest

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to apply: '
        required: true
        type: choice
        default: dev
        options:
        - dev
        - prod
        - all

jobs:
  terraform-deploy-dev:
    if: inputs.environment == 'dev' || inputs.environment == 'all' || inputs.environment == ''

    name: Trigger Applying (dev)
    uses: ./.github/workflows/deploy.yml

    with:
      environment: dev
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  terraform-deploy-prod:
    if: inputs.environment == 'prod' || inputs.environment == 'all'

    name: Trigger Applying (prod)
    uses: ./.github/workflows/deploy.yml

    with:
      environment: prod
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
