name: Terraform Deploy

env:
  TERRAFORM_VERSION: latest

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '**.tf'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to apply: '
        required: true
        type: environment
        default: dev
        options:
        - dev
        - prod
        - all

jobs:
  terraform-deploy-dev:
    name: Terraform - Applying (dev)
    uses: ./.github/workflows/deploy.yml

    with:
      environment: dev
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform-deploy-prod:
    name: Terraform - Applying (dev)
    uses: ./.github/workflows/deploy.yml
    needs: terraform-deploy-dev

    with:
      environment: dev
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
