name: Terraform Destroy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to destroy: '
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    name: Terraform - Applying (${{ inputs.environment }})
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_env: ${{ inputs.environment }}
      TF_VAR_name: ${{ github.event.repository.name }}

    concurrency: 
      group: ${{ inputs.environment }}
      cancel-in-progress: false
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set tfstate_bucket env var
      run: echo "tfstate_bucket=terraform-$(aws sts get-caller-identity | jq -r '.Account')" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      id: init
      run: >
        terraform init \
          -backend-config "region=$TF_VAR_AWS_DEFAULT_REGION" \
          -backend-config "bucket=$tfstate_bucket" \
          -backend-config "key=${{ github.event.repository.name }}"

    - name: Terraform Destroy
      id: apply
      run: terraform destroy -auto-approve
    