name: Destroy Stack

env:
  TERRAFORM_VERSION: latest
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy: '
        required: true
        type: choice
        default: dev
        options:
        - dev
        - prod
        - all

jobs:
  terraform-destroy-dev:
    name: Trigger Destroying (dev)
    uses: ./.github/workflows/destroy.yml

    if: inputs.environment == 'dev' || inputs.environment == 'all' || inputs.environment == ''

    with:
      environment: dev
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_admin_role_arn: ${{ secrets.TF_VAR_ADMIN_ROLE_ARN }}

  terraform-destroy-prod:
    name: Trigger Destroying (prod)
    uses: ./.github/workflows/destroy.yml

    if: inputs.environment == 'prod' || inputs.environment == 'all'

    with:
      environment: prod
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_admin_role_arn: ${{ secrets.TF_VAR_ADMIN_ROLE_ARN }}
