name: 'Terraform - Dev'

on:
  push:
    branches:
    - main

jobs: 
  terraform-apply:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_env: ${{ secrets.ENV }}
      TF_VAR_name: ${{ github.event.repository.name }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    # - name: Terraform Apply
    #   id: apply
    #   run: terraform apply -auto-approve
